
export default {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GET_USERINFO: 'GET_USERINFO',
  USER_INFO: 'USER_INFO',
  REMOVE_USER_INFO: 'REMOVE_USER_INFO',
  NO_LOGIN_OR_LOGIN_FAILED: 'NO_LOGIN_OR_LOGIN_FAILED'
}
